# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "3be30e33-417a-49b7-9c74-7cc34bd7ca40"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :upload do
  increment_build_number

  # build your iOS app
  gym(
    # scheme: "YourScheme",
    export_method: "app-store",
    include_bitcode: true
  )

  # upload to Testflight
  pilot(skip_waiting_for_build_processing: true)
end
